// This file is generated by Prismic local builder. Update with care!

export { default as BannerImage } from './BannerImage'
export { default as RecipeStep } from './RecipeStep'
export { default as TableList } from './TableList'
